Adding initial cloud Structure docs
griptape-ai/griptape pull request #1036
Opened 2024-07-31 21:50 UTC by zachgiordano

- [X] I have read and agree to the contributing guidelines for [submitting new pull requests](https://github.com/griptape-ai/griptape?tab=readme-ov-file#submitting-pull-requests).

## Describe your changes

## Issue ticket number and link

2024-08-01 20:22 UTC, vachillo submitted a review, later dismissed

2024-08-01 21:12 UTC, collindutter requested changes

2024-08-01 21:12 UTC, collindutter commented on docs/griptape-cloud/index.md
> +Managed services for your AI app stack. Deploy and scale end-to-end solutions, from LLM-powered data prep and retrieval to AI agents, pipelines and workflows.
This reads a bit odd, I think it should still start with "Griptape Cloud is...

2024-08-01 21:12 UTC, collindutter commented on docs/griptape-cloud/structures/structure-config.md
> +## Structure Config File
Should start with `## Overview` for consistency with other pages.

2024-08-01 22:20 UTC, zachgiordano commented on docs/griptape-cloud/structures/structure-config.md
> +The Structure Config YAML version number.
I can update this to say "schema" version

2024-08-01 22:24 UTC, zachgiordano commented on docs/griptape-cloud/structures/structure-config.md
> +* **pre_build_install_script** - The path to your pre_build_install_script, for running during the Structure build prior to dependency installation.
yes, I'll update to note that

2024-08-01 22:30 UTC, zachgiordano commented on docs/griptape-cloud/index.md
> +Managed services for your AI app stack. Deploy and scale end-to-end solutions, from LLM-powered data prep and retrieval to AI agents, pipelines and workflows.
I'll link to the managed template and samples. I imagine we'll want to do a rewrite of this main page, so this is just a placeholder.

2024-08-02 15:27 UTC, collindutter submitted a review, later dismissed

2024-08-02 15:50 UTC, vachillo submitted a review, later dismissed

2024-08-02 19:27 UTC, closed without merging