Update task log statement logging levels
griptape-ai/griptape pull request #1059
Opened 2024-08-12 21:41 UTC by vachillo

- [x] I have read and agree to the contributing guidelines for [submitting new pull requests](https://github.com/griptape-ai/griptape?tab=readme-ov-file#submitting-pull-requests).

## Describe your changes
update log levels for tasks so that outputs can be toggled off

## Issue ticket number and link

2024-08-13 16:38 UTC, collindutter commented
After thinking about this some more I'm not sure I'm a fan of moving Task output to `logging.debug` statements since most of the time this is useful information. To keep the same functionality as today we'd have to set griptape's default logging level to `logging.DEBUG` which is ["typically only of interest to a developer trying to diagnose a problem."](https://docs.python.org/3/library/logging.html#logging-levels)

The original ticket is regarding suppressing logs, so why don't we use [filter objects](https://docs.python.org/3/library/logging.html#filter-objects) built into the logging module? If added to the [config module](https://github.com/griptape-ai/griptape/pull/1045), it could look something like this:

```python
import logging

from griptape.structures import Agent
from griptape.tools import WebScraper
from griptape.config import config


class TruncateFilter(logging.Filter):
    MAX_LOG_LENGTH = 1000

    def filter(self, record):
        message = record.getMessage()

        if len(message) > self.MAX_LOG_LENGTH:
            record.msg = f"{message[:self.MAX_LOG_LENGTH]}... [TRUNCATED]"
            record.args = ()
        # Could also return False to prevent the log from being emitted

        return True


config.logging.add_filter(TruncateFilter())


agent = Agent(
    input="Tell me about {{ args[0] }}",
    tools=[
        WebScraper(),
    ],
)
agent.run("https://en.wikipedia.org/wiki/Vim_(text_editor)")
```

2024-08-13 22:29 UTC, collindutter requested changes
Nice 👍 

Looks like docs are not building, and can you please adding a logging section to the existing config doc?

2024-08-13 22:29 UTC, collindutter commented on griptape/config/logging/filters/__init__.py
These can probably just live in `config.logging`, what do you think?

2024-08-13 22:29 UTC, collindutter commented on griptape/config/logging/logging_config.py
> +        [logger.addFilter(logger_filter) for logger_filter in self.logger_filters]
Avoid using list comprehension when the return value is not used.

2024-08-13 22:29 UTC, collindutter commented on griptape/config/logging/logging_config.py
> +        logger.handlers = self.logger_handlers
Is there an `addHandler` method we can use?

2024-08-13 22:40 UTC, vachillo commented on griptape/config/logging/filters/__init__.py
should _everything_ get exported to the top level? wasnt sure what the standard is

2024-08-14 15:57 UTC, collindutter commented
@vachillo all tests appear to be failing

2024-08-14 16:07 UTC, vachillo commented
> @vachillo all tests appear to be failing

missed imports

2024-08-14 18:31 UTC, collindutter commented on docs/griptape-framework/structures/config.md
> +TODO
TODO

2024-08-14 19:00 UTC, vachillo commented on docs/griptape-framework/structures/config.md
> +TODO
bad at words

2024-08-15 16:19 UTC, collindutter approved these changes

2024-08-15 16:31 UTC, merged