Structures, Tools, Tasks, are now serializable.
griptape-ai/griptape pull request #1261
Opened 2024-10-15 16:54 UTC by william-price01

- [ ] I have read and agree to the contributing guidelines for [submitting new pull requests](https://github.com/griptape-ai/griptape?tab=readme-ov-file#submitting-pull-requests).

## Describe your changes
- Added `SerializableMixin` to `Structure`, `BaseTask`, `BaseTool`, `ToolTask`, `TaskMemory`.
- Added `metadata={"serializable": True}` to multiple fields on `Structure`, `BaseTask`, `BaseTool`, `ToolTask`, `TaskMemory`
## Issue ticket number and link

2024-10-15 23:07 UTC, collindutter reviewed
Awesome! I know CodeCov is passing but please add `test_to_dict` tests for each of the classes.

2024-10-15 23:07 UTC, collindutter commented on griptape/tasks/base_task.py
>      max_meta_memory_entries: Optional[int] = field(default=20, kw_only=True)
Let's serialize these

2024-10-16 00:56 UTC, william-price01 commented on griptape/tasks/base_task.py
>      max_meta_memory_entries: Optional[int] = field(default=20, kw_only=True)
sounds good!

2024-10-16 00:57 UTC, william-price01 commented on CHANGELOG.md
> +- `TaskMemory` now utilizes `SerializableMixin` for serialization.
got ya.

2024-10-16 23:10 UTC, collindutter approved these changes
Fantastic work!

2024-10-16 23:45 UTC, collindutter requested changes

2024-10-16 23:45 UTC, collindutter commented on tests/unit/memory/tool/test_task_memory.py
> +        assert len(deserialized_memory.load_artifacts("test")) == 2
Rename `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/structures/test_agent.py
> +        assert deserialized_agent.task_outputs[task.id].value == "mock output"
Rename to `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/structures/test_pipeline.py
> +        assert deserialized_pipeline.task_outputs[task.id].value == "mock output"
Rename to `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/structures/test_workflow.py
> +        assert deserialized_workflow.task_outputs[task.id].value == "mock output"
Rename to `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/tasks/test_base_task.py
> -        result = task.add_parent(parent)
Why was this removed?

2024-10-16 23:45 UTC, collindutter commented on tests/unit/tasks/test_base_task.py
> +        assert workflow.tasks[0].output.value == "foobar"
Rename to `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/tasks/test_tool_task.py
> +        assert isinstance(deserialized_tool_task, ToolTask)
Rename to `test_to_dict` and `test_from_dict`

2024-10-16 23:45 UTC, collindutter commented on tests/unit/tools/test_base_tool.py
> +        assert deserialized_tool.execute(tool.test_list_output, ActionsSubtask("foo"), action).to_text() == "foo\n\nbar"
Rename to `test_to_dict` and `test_from_dict`

2024-10-17 16:16 UTC, collindutter approved these changes
Great work!

2024-10-17 16:32 UTC, merged