Replace hardcoded prompt with Jinja template
griptape-ai/griptape pull request #137
Opened 2023-07-25 05:20 UTC by joelwiesmann

Replace hardcoded vector query engine prompt with Jinja template.

2023-07-25 18:24 UTC, vasinov requested changes
Thanks for the PR! This is a much needed improvement.

2023-07-25 18:24 UTC, vasinov commented on griptape/engines/query/vector_query_engine.py
>              next_segment = f'\n\nText segment:\n"""\n{artifact.value}\n"""'
We should be able to tuck "Text segment" into a template as well and just use a for loop there:

```
{% for segment in text_segments %}
...
{% endfor %}
```

2023-07-25 18:24 UTC, vasinov commented on griptape/engines/query/vector_query_engine.py
> +                metadata=metadata or "-",
Probably can keep it as `metadata` and not include it in the prompt at all if it's none:

```
{% if metadata %}Metadata: {{ metadata }}{% endif %}
```

2023-07-25 21:52 UTC, vasinov requested changes
This is so great! One last thing: could you please add a couple of unit tests with a custom template just to make sure text segments are appended correctly? Thanks!

2023-07-25 21:56 UTC, joelwiesmann commented
> This is so great! One last thing: could you please add a couple of unit tests with a custom template just to make sure text segments are appended correctly? Thanks!

Sure! Will have a look on that tomorrow. Will consider this in the future from the beginning :-).

2023-07-26 12:51 UTC, joelwiesmann commented
@vasinov I'm not sure what you meant by "custom template", so I added a test case to see, whether the provided metadata / text segments & question end up in the created prompt at all. This case is expected to work with whatever query template is used.

2023-07-26 15:20 UTC, merged