Don't retry invalid request to openai
griptape-ai/griptape pull request #187
Opened 2023-08-28 23:34 UTC by collindutter

Draft PR for #148

2023-08-28 23:51 UTC, vasinov reviewed
We could add `ignored_exception_types: List[Type[Exception]]` to `ExponentialBackoffMixin` and set that in each subclass instead.

2023-08-28 23:53 UTC, collindutter commented
I like that more, will update tomorrow.

2023-09-15 20:00 UTC, vasinov requested changes

2023-09-15 20:00 UTC, vasinov commented on griptape/drivers/prompt/openai_completion_prompt_driver.py
> +    ignored_exception_types: Tuple[Type[Exception], ...] = field(default=(openai.InvalidRequestError), kw_only=True)
This default needs to be wrapped in a `Factory`.

2023-09-15 20:00 UTC, vasinov commented on griptape/drivers/prompt/openai_chat_prompt_driver.py
> +    ignored_exception_types: Tuple[Type[Exception], ...] = field(default=(openai.InvalidRequestError), kw_only=True)
This default needs to be wrapped in a `Factory`.

2023-09-15 20:00 UTC, vasinov commented on griptape/mixins/exponential_backoff_mixin.py
> +    ignored_exception_types: Tuple[Type[Exception], ...] = field(default=(), kw_only=True)
Should be `factory=tuple`.

2023-09-18 16:35 UTC, closed without merging