Add customization to Chat util output
griptape-ai/griptape pull request #215
Opened 2023-09-12 18:55 UTC by collindutter

Addresses https://github.com/griptape-ai/griptape/issues/66.

Enables use cases like:
```python
from griptape.structures import Agent
from griptape.rules import Ruleset, Rule
from griptape.utils import Chat

pirate_agent = Agent(
    rulesets=[
        Ruleset(
            name="Pirate",
            rules=[
                Rule("You are a pirate"),
                Rule("You are worried about people stealing your gold"),
            ],
        )
    ]
)

Chat(
    pirate_agent,
    exit_keywords=["exit", "arr!"],
    processing_text="Arr, processing...",
    exiting_text="Arr, catch ye later...",
    intro_text="Arr - I be a pirate. Please chat with me!",
).start()
```

```
Arr - I be a pirate. Please chat with me!
Q: Where is your treasure?
Arr, processing...
[09/12/23 11:51:16] INFO     PromptTask b1a5ffe067e743a8b693b979cfac37bc
                             Input: Where is your treasure?
[09/12/23 11:51:25] INFO     PromptTask b1a5ffe067e743a8b693b979cfac37bc
                             Output: Arr matey, ye be a bit too curious, aren't ye? As a pirate, I can't be sharin' the whereabouts of me
                             precious gold. There be too many scurvy dogs out there lookin' to pilfer me hard-earned loot. Ye understand,
                             don't ye?
A: Arr matey, ye be a bit too curious, aren't ye? As a pirate, I can't be sharin' the whereabouts of me precious gold. There be too many scurvy dogs out there lookin' to pilfer me hard-earned loot. Ye understand, don't ye?
Q: arr!
Arr, catch ye later...
```

2023-09-12 19:29 UTC, shhlife commented
Can we also provide prompt customization? So instead of Q: and A: we could have something like:

```
prompt_text = "Hey:",
response_text = "Arr:"
```

2023-09-12 19:40 UTC, collindutter commented
@shhlife yep, updated!

2023-09-14 16:45 UTC, vasinov requested changes

2023-09-14 16:45 UTC, vasinov commented on griptape/utils/chat.py
> +            print(self.intro_text)
Can we also make `print` customizable? May be something like this:

```python
output_message: Callable[[str], None] = field(
    default=Factory(lambda: print),
    kw_only=True
)
```

2023-09-20 23:22 UTC, vasinov approved these changes

2023-09-20 23:22 UTC, vasinov commented on griptape/utils/chat.py
> +    output_fn: Callable[[str], None] = field(default=Factory(lambda: print), kw_only=True)
We use `func` in `SnowflakeSqlDriver.connection_func` and `fn` in `LocalVectorStoreDriver.relatedness_fn`. Some other callables look like regular methods (i.e., verb, no suffix).

Not sure what to do here. Just go with `fn` and address the rest later?

2023-09-21 15:49 UTC, merged