Improve embedding drivers coverage
griptape-ai/griptape pull request #253
Opened 2023-09-20 20:34 UTC by dylanholmes

### Notes

Partially resolves #130:
- Increase the unit testing coverage of the embedding drivers to 100%
- Add coverage configuration file to ignore non-meaningful lines and include branch coverage.

Note that you can view the coverage results in vs code using the "Coverage Gutters" extension if you generate the xml report.

### Testing

Command used to check coverage (from poetry shell):
```
pytest tests/unit/drivers/embedding --cov=griptape/drivers/embedding
```

Coverage before commit:
```
Name                                                           Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------------------------------------
griptape/drivers/embedding/__init__.py                             0      0      0      0   100%
griptape/drivers/embedding/azure_openai_embedding_driver.py       14      0      4      0   100%
griptape/drivers/embedding/base_embedding_driver.py               13      0      6      1    95%
griptape/drivers/embedding/bedrock_titan_embedding_driver.py      20      0      8      0   100%
griptape/drivers/embedding/openai_embedding_driver.py             46      2     12      2    93%
------------------------------------------------------------------------------------------------
TOTAL                                                             93      2     30      3    96%
```

Coverage after commit:
```
Name                                                           Stmts   Miss Branch BrPart  Cover
------------------------------------------------------------------------------------------------
griptape/drivers/embedding/__init__.py                             0      0      0      0   100%
griptape/drivers/embedding/azure_openai_embedding_driver.py       14      0      4      0   100%
griptape/drivers/embedding/base_embedding_driver.py               13      0      6      0   100%
griptape/drivers/embedding/bedrock_titan_embedding_driver.py      20      0      8      0   100%
griptape/drivers/embedding/openai_embedding_driver.py             46      0     12      0   100%
------------------------------------------------------------------------------------------------
TOTAL                                                             93      0     30      0   100%
```

2023-09-20 22:04 UTC, collindutter requested changes
Thank you for the PR @dylanholmes!

2023-09-20 22:24 UTC, dylanholmes commented on .coveragerc
Agreed, I think it should replace [pytest-cover](https://pypi.org/project/pytest-cover/), which is deprecated.

Want me to do that as a part of this PR?

2023-09-20 22:26 UTC, collindutter commented on .coveragerc
Ah good call out! I'd be fine with having as part of this PR, @vasinov what do you think?

2023-09-20 22:30 UTC, dylanholmes commented on tests/unit/drivers/embedding/test_openai_embedding_driver.py
> +        assert OpenAiEmbeddingDriver().try_embed_string("foobar " * 5000) == [0, 1, 0]
It is intentional (to ensure that the code hits the long-string branch, which I found surprising to be necessary). I had considered the option wasn't sure what the response would be so I went with the less-character solution. Thanks for taking a stance and suggesting an alternative!

I'll change it as you suggested to make the intention more obvious.

2023-09-20 22:45 UTC, dylanholmes commented on .coveragerc
Btw, I just went ahead and updated it.  Let me know if you want me to undo it

> There shouldn't really be any differences, since pytest-cover 3 has a dependency on the latest coverage and pytest-cov packages.

2023-09-20 22:46 UTC, collindutter approved these changes

2023-09-20 22:47 UTC, collindutter commented on .coveragerc
Thanks! I suspect it will be fine.

2023-09-21 00:25 UTC, collindutter approved these changes

2023-09-24 20:51 UTC, vasinov submitted a review, later dismissed

2023-09-25 15:17 UTC, merged