Added extra parameters to TextSummaryTask
griptape-ai/griptape pull request #277
Opened 2023-09-23 04:05 UTC by ashkaaar

Added the parameters regarding the issue https://github.com/griptape-ai/griptape/issues/203

length
target audience
format

Unit tests: passed
waiting for review and suggestions

2023-09-24 21:02 UTC, vasinov requested changes
Thanks for the PR!

2023-09-24 21:02 UTC, vasinov commented on griptape/engines/summary/base_summary_engine.py
> +    def summarize_text(self, text: str, length: int = None, target_audience: str = None, format: str = None) -> str:
Those should be class properties for:
- DRYness across class methods and
- ease of integration with tasks and `TextMemoryActivitiesMixin.summarize`.

2023-09-24 21:02 UTC, vasinov commented on griptape/engines/summary/base_summary_engine.py
> +    def summarize_text(self, text: str, length: int = None, target_audience: str = None, format: str = None) -> str:
Additionally, we always use `Optional`s in type hints if the default value is `None`. In this case it should be `Optional[int]`, `Optional[str]`, and `Optional[str]`.

2023-10-24 23:23 UTC, collindutter commented
@ashkaaar I am going to close this PR in favor of the work that will be done on https://github.com/griptape-ai/griptape/issues/342. Implementing this functionality as described in the other issue gives users more control over the output, and it provides a more consistent experience across Tasks.

2023-10-24 23:23 UTC, closed without merging

2023-10-25 18:05 UTC, collindutter commented
No problem at all! Thanks for the original PR 🙂