Add rules to all Tasks
griptape-ai/griptape pull request #415
Opened 2023-11-03 17:17 UTC by collindutter

2023-11-05 17:14 UTC, vasinov requested changes
What a great change!

All templates that render `{{ rulesets }}` should probably do it conditionally, so we don't end up with extra blank lines in the prompt when there are no `rulesets`.

Otherwise, looks good to me.

2023-11-06 22:32 UTC, vasinov requested changes

2023-11-06 22:32 UTC, vasinov commented on griptape/templates/engines/summary/prompt_summary.j2
> +{{ rulesets }}
Cleanup.

2023-11-06 22:35 UTC, collindutter commented on griptape/templates/engines/summary/prompt_summary.j2
> +{{ rulesets }}
Oops, fixed

2023-11-06 23:38 UTC, vasinov approved these changes

2023-11-06 23:39 UTC, merged