Add pre-commit configuration to apply Black formatting
griptape-ai/griptape pull request #418
Opened 2023-11-06 15:01 UTC by andrewfrench

Adds local pre-commit configuration to enforce Black formatting. If code is not formatted appropriately, the Code Checks workflow will fail. The README has been updated with info on formatting expectations and how to configure `pre-commit`, which has been added as a dependency using `poetry`. 

Configure `pre-commit` using `poetry`:

```
poetry run pre-commit install
```

⚠️ Note: this PR also increases the line length configuration from 80 to 120. The large diff is due to running Black after making this change.

Closes #426

2023-11-06 15:33 UTC, andrewfrench commented on .github/actions/init-environment/action.yml
> +          fetch-depth: 0
Required to support commits in later steps, avoiding `detached HEAD` issue.

2023-11-06 15:34 UTC, andrewfrench commented on griptape/tasks/text_query_task.py
> +        )
Reformatting here comes from currently failing style checks on `dev`.

2023-11-06 16:47 UTC, collindutter commented on .github/workflows/autoformat.yml
I had originally named this `code-checks.yml` because I thought we might have other checks (linting, static type checking) in the future. But maybe it's a good idea to separate workflows that make direct changes to the branch vs workflows that just check it.

2023-11-06 18:34 UTC, andrewfrench commented on .github/workflows/autoformat.yml
Black formatting was the only job in the workflow, so I felt the name was misleading once it was updated to autocommit. If we want to keep code formatting/style/static analysis stuff in this file I can change the name back.

2023-11-08 00:45 UTC, collindutter commented
@andrewfrench based on the number of files changed I assume you also changed the line length to 120?

2023-11-08 00:55 UTC, andrewfrench commented on .github/workflows/autoformat.yml
Retained the original Code Checks naming as this now uses pre-commit and PR checks rather than autocommits.

2023-11-08 16:28 UTC, collindutter requested changes

2023-11-08 16:28 UTC, collindutter commented on pyproject.toml
> +pre-commit = "^3.5.0"
@andrewfrench move this to the `dev` [group](https://python-poetry.org/docs/master/managing-dependencies/). And we should probably add a bit to the contributing guidelines that says they'll need to install dev dependencies via `poetry install --with dev`.

2023-11-08 17:44 UTC, collindutter approved these changes

2023-11-08 20:34 UTC, collindutter approved these changes

2023-11-08 20:35 UTC, vasinov submitted a review, later dismissed

2023-11-08 20:55 UTC, collindutter approved these changes

2023-11-08 20:55 UTC, merged