feat: add lambda executor
griptape-ai/griptape pull request #48
Opened 2023-05-16 23:55 UTC by collindutter

2023-05-16 23:57 UTC, collindutter commented
Relevant to https://github.com/griptape-ai/griptape/issues/43

2023-05-17 07:10 UTC, vasinov requested changes
So, overall, this would only work if the whole structure is executed inside of a lambda function. It doesn't seem like we need a standalone executor to achieve whatever this new class is doing. All of those changes can be applied to the `LocalExecutor` to make it more versatile.

I think we should still consider building a standalone `AwsLambdaExecutor` that runs tools inside of lambda functions separately from where structures are executed. Basically, the same idea as the `DockerExecutor`.

2023-05-17 07:10 UTC, vasinov commented on griptape/executors/lambda_executor.py
> +        deps_dir = f'/tmp/deps/{tool_name}/' if self.install_dependencies else '/var/task/'
Can we move the `/tmp/deps` and `/var/task` into a class-level const?

2023-05-17 07:10 UTC, vasinov commented on griptape/executors/lambda_executor.py
> +            f'from sys import path; path.insert(1, "{deps_dir}"); from tool import {tool_name}; print({tool_name}().{tool_activity.__name__}({input_value}))'
I think those are starting to get long. We should just use string joins. Can you break this up into a list, join it with `str.join(";", <list name>)`, and apply the same pattern to other executors?

2023-05-22 18:44 UTC, closed without merging