feat: add claude prompt driver
griptape-ai/griptape pull request #64
Opened 2023-06-03 16:02 UTC by collindutter

Should we call this ClaudePromptDriver or AnthropicPromptDriver?

2023-06-03 16:14 UTC, vasinov requested changes
Let's also at the very least add an init test similar to `TestCoherePromptDriver.test_init`. Ideally, we should start adding mocked out tests for all drivers but that should probably be a separate issue in the tracker.

2023-06-03 16:14 UTC, vasinov commented on griptape/drivers/prompt/claude_prompt_driver.py
> +class ClaudePromptDriver(BasePromptDriver):
Let's call it `AnthropicPromptDriver`, since there will likely be other models from Anthropic in the future.

2023-06-03 16:14 UTC, vasinov commented on griptape/drivers/prompt/claude_prompt_driver.py
> +            stop_sequences = [anthropic.HUMAN_PROMPT],
Add `self.tokenizer.stop_sequence` to this, so the model stops at "Observation:"

2023-06-03 16:14 UTC, vasinov commented on griptape/drivers/prompt/claude_prompt_driver.py
> +            prompt=f"{anthropic.HUMAN_PROMPT}{value}{anthropic.AI_PROMPT}",
Could you add a brief comment here explaining why the prompt has to be formed this way?

2023-06-03 16:14 UTC, vasinov commented on griptape/drivers/prompt/claude_prompt_driver.py
> +            max_tokens_to_sample=100,
This needs to come from the tokenizer.

2023-06-03 16:14 UTC, vasinov commented on griptape/drivers/prompt/claude_prompt_driver.py
> +    )
Based on their docs, looks like we need a separate `AnthropicTokenizer`.

2023-06-03 20:38 UTC, vasinov commented on griptape/drivers/prompt/anthropic_prompt_driver.py
> +    api_key: str = field(kw_only=True, metadata={"env": "ANTHROPIC_API_KEY"})
Don't need metadata here.

2023-06-03 23:26 UTC, vasinov commented
@collindutterm this is pretty much ready to be merged except for tests, right?

2023-06-07 04:23 UTC, collindutter commented
> 

Yeah, but I'm running into some odd behavior from their tokenizer now that I'm creating tests.

2023-06-07 04:41 UTC, collindutter commented
@vasinov added tests. Though I still haven't done much real world testing outside hello world.

2023-06-07 23:28 UTC, vasinov requested changes
Apart from the two minor comments, looks ready to be merged!

2023-06-08 14:32 UTC, collindutter commented on griptape/tokenizers/anthropic_tokenizer.py
> +    DEFAULT_MODEL = "claude-v1"
Yeah might as well. Can’t find anything online that indicates it’s more expensive or less performant.

2023-06-09 00:15 UTC, vasinov approved these changes

2023-06-09 00:31 UTC, merged