Add Mistral support to Bedrock
griptape-ai/griptape pull request #703
Opened 2024-03-20 23:32 UTC by collindutter

Closes #664

2024-03-25 17:46 UTC, dylanholmes requested changes

2024-03-25 17:46 UTC, dylanholmes commented on griptape/drivers/prompt_model/bedrock_mistral_prompt_model_driver.py
> +        system_input = next((i for i in prompt_stack.inputs if i.is_system()), None)
Why does this assume a max of one system input?

Should you raise an exception if this assumption violated (rather than ignoring silently)?

2024-03-25 17:46 UTC, dylanholmes commented on griptape/drivers/prompt_model/bedrock_mistral_prompt_model_driver.py
> +                prompt_lines.append(f"[INST] {prompt_input.content} [/INST]")
Won't this end up with unbalanced BOS/EOS tokens? I didn't quickly get a great understanding of the mistrial docs on hugging face. Is unbalanced BOS/EOS tokens ok?

2024-06-03 17:59 UTC, collindutter commented
Going to close this in favor of the work that will be done for [this](https://github.com/griptape-ai/griptape/issues/818). Prompt Model Drivers may become a thing of the past.

2024-06-03 17:59 UTC, closed without merging